webshopnew/config/routes.rb
Webshopnew::Application.routes.draw do

  get "login" => "sessions#new", :as => "new_session"
  get "logout" => "sessions#destroy", :as => "logout"

  get "signup" => "users#new", :as => "new_user"

  root :to => "users#index"

  resources :reviews

  resources :users , :except => [:new]

  resources :products do
    member do
      put 'publish'
      put 'unpublish'
    end
    collection do
      put 'public_all'
      put 'unpublic_all'
    end
    resources :reviews, :except => [:show, :destroy]
  end

  resources :sessions , :except => [:new]

end

webshopnew/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, :notice => 'Review was successfully created.' }
        format.json { render :json => @review, :status => :created, :location => @review }
      else
        format.html { render :action => "new" }
        format.json { render :json => @review.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, :notice => 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @review.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

webshopnew/app/helpers/reviews_helper.rb
module ReviewsHelper
end

webshopnew/app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

webshopnew/app/views/reviews/_review.html.erb
<tr>
  <td><%= review.summary %></td>
  <td><%= review.description %></td>
  <td><%= review.rating %></td>
  <td><%= link_to 'Show', product_path(review) %></td>
  <td><%= link_to 'Edit', edit_product_review_path(@product, review) %></td>
</tr>

webshopnew/app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Back', product_path %>

webshopnew/app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Summary</th>
    <th>Description</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <%= render @reviews %>
</table>
<br />

webshopnew/app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

webshopnew/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Summary:</b>
  <%= @review.summary %>
</p>

<p>
  <b>Description:</b>
  <%= @review.description %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>


<%= link_to 'Edit', edit_product_review_path(@review) %> |
<%= link_to 'Back', product_reviews_path %>