webshopnew/config/routes.rb
Webshopnew::Application.routes.draw do

  get "login" => "sessions#new", :as => "new_session"
  get "logout" => "sessions#destroy", :as => "logout"

  get "signup" => "users#new", :as => "new_user"

  root :to => "users#index"

  resources :reviews

  resources :users , :except => [:new]

  resources :products do
    member do
      put 'publish'
      put 'unpublish'
    end
    collection do
      put 'public_all'
      put 'unpublic_all'
    end
    resources :reviews, :except => [:show, :destroy]
  end

  resources :sessions , :except => [:new]

end

webshopnew/app/views/layouts/_menu.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webshopnew</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <tr class="menu2">
    <td class="logo"><%= image_tag("images.jpeg") %></td>
    <td class="menu2"><%= link_to 'Users',    users_path %></td>
    <td class="menu2"><%= link_to 'Products',    products_path %></td>
    <td class="menu2"><%= link_to 'Reviews',    reviews_path %></td>
  </tr>
</nav>
</body>
</html>

webshopnew/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webshopnew</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? %>
<p class="menu2"><%= "Usuario: email:#{current_user.email} | nombre:#{current_user.first_name}" %></p>
    <% else %>
<p>Haz login <%= link_to 'aquí', new_session_path %></p>
    <% end %>
<header class="menu2">
  <%=render 'layouts/menu' %>
</header>
<div class="body">
<%= yield %>
</div>
</body>
</html>